- name: Send Discord embed
  run: |
    python3 - <<EOF
    import os, json, requests

    payload = {
      "embeds": [{
        "title": "New Release: ${{ github.event.release.tag_name }}",
        "url": "${{ github.event.release.html_url }}",
        "description": """${{ github.event.release.body }}""",
        "color": 5814783
      }]
    }

    requests.post(
      os.environ["WEBHOOK"],
      json=payload
    )
    EOF
  env:
    WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
